<?php
/**
 * @file
 * Code for the exhibition_content feature.
 */

include_once 'exhibition_content.features.inc';


/**
 * Implementation of hook_clone_node_alter().
 */
function exhibition_content_clone_node_alter(&$node, $context) {
  // Unset those field that should probably be changed when cloning a 'visual'.
  if ('visual' == $context['original_node']->type) {
    unset($node->field_visual_caption);
    unset($node->field_image_file);
    unset($node->field_video_file);
    unset($node->field_tag);
  }
}


/**
 * Implementation of hook_form_alter().
 */
function exhibition_content_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['field_visual_caption'])) {
    // Display input elements for all language version of field_visual_caption.
    exhibition_content_form_display_field_multilingual($form, 'field_visual_caption');
  }

  if (isset($form['field_embed_code']) && count(array_intersect($GLOBALS['user']->roles, array('administrator', 'chiefeditor')))) {
    $form['field_embed_code']['#access'] = FALSE;
  }

  if (in_array($form_id, array('visual_node_form', 'page_node_form'))) {
    // Make a 'visual' node's title non-required (auto-filled in hook_entity_presave.
    $form['title']['#required'] = FALSE;
  }

  if ('portrait_node_form' == $form_id) {
    // Disable a "portrait" node's 'visuals' field from being edited.
    $form['field_visual']['#disabled'] = TRUE;
  }
}


/**
 * Implementation of hook_views_bulk_operations_form_alter().
 */
function exhibition_content_views_bulk_operations_form_alter(&$form, &$form_state, $vbo) {
  if($form['#form_id'] == 'views_form_admin_content_page'){
    //    unset($form['select']['#title']);
    //    $form['select']['#type'] = 'container';
    $form['select']['#collapsible'] = TRUE;
    $form['select']['#collapsed'] = TRUE;
  }
}


/**
 * Offer form element for all languages for a given text field in a given form.
 */
function exhibition_content_form_display_field_multilingual(&$form, $field_name) {
  $languages = language_list();
  $node = $form['#node'];
  $field = &$form[$field_name];
  $field_element = element_children($field);
  $field_element = array_pop($field_element);
  $field_element = $field[$field_element];
  $el_key = 'multilang:' . $field_name;
  $el = array(
    '#type' => 'container',
    '#weight' => $field['#weight'],
    '#description' => $field_element['#description'],
    '#attributes' => $field['#attributes'],
    '#field_name' => $field_name,
  );
  $el['#attributes']['class'][] = 'multilang-elements';

  $form['#group_children'][$el_key] = $form['#group_children'][$field_name];

  foreach ($languages as $lang_key => $language) {
    if ($language->enabled) {
      $el_sub_key = $el_key . ':' . $lang_key;
      $el[$el_sub_key] = array(
        '#type' => $field_element[0]['value']['#type'],
        '#language' => $lang_key,
        '#title' => t($language->name),
        '#attributes' => array('class' => array('multilang-element')),
        '#default_value' => isset($node->{$field_name}[$lang_key]) ? $node->{$field_name}[$lang_key][0]['value'] : '',
      );
      if (!isset($el['#title'])) {
        $el['#title'] = $field_element['#title'];
        $el[$el_sub_key]['#title'] = $el['#title'] . ': ' . $el[$el_sub_key]['#title'];
      }
    }
  }

  $el['description'] = array('#markup' => '<div>' . $field_element['#description'] . '</div>');
  $form[$el_key] = $el;
  $form['#multilang_elements'][] = $el_key;
  $field['#access'] = FALSE;
}


/**
 * Implementation of hook_node_submit().
 *
 * Transfer Multi-lang-element values to the corresponding fields.
 */
function exhibition_content_node_submit($node, $form, &$form_state) {
  $languages = language_list();
  if (isset($form['#multilang_elements'])) {
    foreach($form['#multilang_elements'] as $el_key) {
      $el = $form[$el_key];
      $field_name = $el['#field_name'];
      foreach ($languages as $lang_key => $language) {
        if ($language->enabled) {
          $el_sub_key = $el_key . ':' . $lang_key;
          $value = $form_state['values'][$el_sub_key];
          // Don't use check_plain here, but in the output, since it screws up the editing with escaped htmlentites.
          // But we do filter_xss here for security.
          $value = filter_xss($value);
          $node->{$field_name}[$lang_key][0]['value'] = $value;
          if (trim($value) && !isset($node->translations->data[$lang_key])) {
            $node->translations->data[$lang_key] = array(
              'entity_type' => 'node',
              'entity_id' => $node->nid,
              'revision_id' => $node->vid,
              'language' => $lang_key,
              'source' => $node->translations->original,
              'uid' => $GLOBALS['user']->uid,
              'status' => 1,
              'translate' => 0,
              'created' => REQUEST_TIME,
              'changed' => REQUEST_TIME,
            );
          }
        }
      }
    }
  }
}


/**
 * Implementation of hook_entity_presave().
 */
function exhibition_content_entity_presave($entity, $type) {
  // Auto-Fill/-Update automated title for 'visual' nodes.
  $e = entity_metadata_wrapper('node', $entity);
  if ('node' == $type) {
    // Derive title for "visual" nodes.
    if (('visual' == $entity->type) && (('' == trim($entity->title)) || ('@' == $entity->title[0]) || ('Clone of' == substr($entity->title, 0, 8)) )) {
      $title = array();
      $title[] = $entity->field_parent_content[LANGUAGE_NONE] ? $e->field_parent_content->title->value() : NULL;
      $title[] = $entity->field_epoch[LANGUAGE_NONE]          ? $e->field_epoch->name->value() : NULL;
      $title[] = $entity->field_visual_purpose[LANGUAGE_NONE] ? $e->field_visual_purpose->value() : NULL;
      $title[] = $entity->field_image_file[LANGUAGE_NONE]     ? $e->field_image_file->file->name->value() : NULL;
      $title[] = $entity->field_video_file[LANGUAGE_NONE]     ? $e->field_video_file->file->name->value() : NULL;
      $entity->title = '@' . array_reduce($title, function($carry, $item) {
          if ($item) {
            $carry = $carry ? $carry . ' | ' : '';
            $carry .= $item;
          }
          return $carry;
        });
    }
    // Derive title for "page" nodes.
    if (  ('page' == $entity->type)  &&  ('' == trim($entity->title))  ) {
      $entity->title = $e->field_headline->value();
    }
  }
}


/**
 * Implementation of hook_entity_view().
 */
function exhibition_content_entity_view($entity, $type, $view_mode, $langcode) {
  $build = &$entity->content;
  $entity_type = $type;
  $bundle = ('node' == $type) ? $entity->type : NULL;

  if (('node' == $entity_type) && ('portrait' == $bundle)) {
    // Construct the portrait teaser from its feature visuals.
    if ('full' == $view_mode) {
      $build += exhibition_content_prepare_portrait_full_view($entity);
    }
    // Construct the portrait full view from its visuals and fields.
    else {
    }
  }

  // Replace content embed code [content:NODE_ID:VIEW_MODE:[LEFT|RIGHT]] with respective content rendering.
  if (isset($entity->content['field_text'])) {
    $entity->content['field_text'][0]['#markup'] =
      preg_replace_callback(
        '/\[.*\]/U',
        function ($matches) {
          @list($embed_code, $embed_id, $embed_viewmode, $embed_layout) = explode(':', substr($matches[0], 1, -1));
          $embed_layout = empty($embed_layout) ? '' : 'content-embed-' . drupal_html_class($embed_layout);
          $node_viewed = node_view(node_load($embed_id), $embed_viewmode);
          return '<div class="content-embed ' . $embed_layout . '">' . render($node_viewed) . '</div>';
        },
        $entity->content['field_text'][0]['#markup']
      );
  }
}


/**
 * Prepares render array for a given portrait's full view.
 */
function exhibition_content_prepare_portrait_full_view($portrait) {
  $build = array();

  $all_visuals = exhibition_content_get_sub_content($portrait->nid, true);

  // Get epoch terms (i.e. correctly ordered by their weight+name).
  $epoch_vocabulary = taxonomy_vocabulary_machine_name_load('epoch');
  $epochs = taxonomy_term_load_multiple(array(), array('vid' => $epoch_vocabulary->vid));

  // Determine feature visual for each epoch, so we can always display the latest one.
  $feature_visuals = array();
  foreach($epochs as $epoch_tid => $epoch_term) {
    if (isset($all_visuals[$epoch_tid]['featured'])) {
      $feature_visuals[$epoch_tid] = $all_visuals[$epoch_tid]['featured'];
      unset($all_visuals[$epoch_tid]['featured']);
    }
  }
  $feature_visuals_originals = $feature_visuals;

  // Loop through all epochs and assemble/extend build array with the visuals for that epoch.
  $epoch_counter = 0;
  foreach($epochs as $epoch_tid => $epoch_term) {
    if (!empty($all_visuals[$epoch_tid]))
    {
      $visuals = $all_visuals[$epoch_tid];

      // Add timeline thread.
      if ($epoch_counter) {
        $build[] = array(
          '#markup' => '<div class="timeline-container"><span class="timeline-thread"></span></div>',
        );
      }

      // First, add featured main visual.
      // Either use the one for this epoch, or, if that is empty, get the most recent one not used yet.
      $feature_visual = NULL;
      $feature_visual_caption = NULL;
      if (isset($feature_visuals[$epoch_tid])) {
        $feature_visual = $feature_visuals[$epoch_tid];
      } else if (!$epoch_counter) {
        list($feature_visual_key) = array_keys($feature_visuals);
        if (!empty($feature_visual_key)) {
          $feature_visual = $feature_visuals[$feature_visual_key];
          unset($feature_visuals[$feature_visual_key]);
        }
      }
      if (!empty($feature_visual)) {
        $build['feature-'.$epoch_tid] = $feature_visual['render'];
      }


      // Add container for the details of the epoch.
      $build[$epoch_tid] = array(
        '#type' => 'container',
        '#attributes' => array('class' => array('details', 'clearfix')),
      );

      // Add tile for the time epoch.
      if (isset($feature_visuals_originals[$epoch_tid])) {
        $feature_visual_caption = reset($feature_visuals_originals[$epoch_tid]['render']['node']);
        $feature_visual_caption = (isset($feature_visual_caption['field_visual_caption']) ? strip_tags($feature_visual_caption['field_visual_caption'][0]['#markup']) : '');
      }
      else if (EXHIBITION_BASE_ID_EPOCH_2015 == $epoch_tid) {
        $feature_visual_caption = t('My new photos from <a href="@url">#everydaysrebrenica at Instagram</a>.', array('@url' => EXHIBITION_BASE_INSTAGRAM_PAGE_URL));
      }
      else {
        $feature_visual_caption = '';
      }
      $epoch_tile = array(
        '#theme' => 'tile',
        '#tile_style' => 0,
        '#tile_class' => 'info-tile',
        '#tile_title' => $epoch_term->name,
        '#tile_caption' => $feature_visual_caption,
        '#tile_visual' => array('#markup' => ' '),
      );
      $build[$epoch_tid][] = $epoch_tile;

      // Third, add all the contents for that time epoch.
      ksort($visuals);
      foreach($visuals as $visual) {
        $render = entity_view('node', array($visual), 'detail');
        $build[$epoch_tid][] = $render;
      }

      // Count up
      $epoch_counter++;
    }
  }
  return $build;
}


/**
 * Get the 'visual' type nodes associated with a given parent node id.
 *
 * Grouped by epoch, if $grouped is true.
 * Ordered by priority.
 */
function exhibition_content_get_sub_content($parent_nid) {
  $build = array();
  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'node')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_parent_content', 'target_id', $parent_nid)
    ->range(0, 100);

  $result = $query->execute();

  if (isset($result['node'])) {
    $nodes = entity_load('node', array_keys($result['node']));
    foreach($nodes as $node) {
      $key      = @$node->field_epoch[LANGUAGE_NONE][0]['tid'];
      $purpose  = @$node->field_visual_purpose[LANGUAGE_NONE][0]['value'];
      if ('featured' == $purpose) {
        $sub_key = 'featured';
        $render = entity_view('node', array($node), 'feature');
        $build[$key][$sub_key] = array('entity' => $node, 'render' => $render);
      }
      $sub_key = @$node->field_priority[LANGUAGE_NONE][0]['value'];
      $sub_key .= '-' . (9999999999 - $node->created) . '-' . $node->nid;
//      if (isset($build[$key][$sub_key])) {
//        $sub_key .= '-2';
//      }
      $build[$key][$sub_key] = $node;
    }
  }

  return $build;
}


/**
 * Get the overview page content
 *
 */
function exhibition_content_get_overview_content($pager = 0) {
  $main_featured_visuals = array();
  $build = array();

  // Query nodes.
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', array('visual'))
    ->propertyCondition('status', NODE_PUBLISHED)
    ->propertyOrderBy('created', 'DESC')
    ->range($pager, 1000);
  $result = $query->execute();

  // If empty result, return empty build.
  if (!isset($result['node'])) { return $build; }

  // Load nodes.
  $nodes = entity_load('node', array_keys($result['node']));

  // Mark latest feature visuals for each portrait.
  foreach($nodes as $nid => $node) {
    $purpose  = @$node->field_visual_purpose[LANGUAGE_NONE][0]['value'];
    $parent = isset($node->field_parent_content[LANGUAGE_NONE][0]['target_id']) ? $node->field_parent_content[LANGUAGE_NONE][0]['target_id'] : 0;
    if (!isset($main_featured_visuals[$parent]) &&  ('featured' == $purpose)) {
      $node->main_featured_visual = TRUE;
      $node->style_override = 'teaser-big';
      $main_featured_visuals[$parent] = $node;
      unset($nodes[$nid]);
    }
  }

  // Split main featured visuals in 1/3 (=> for $above) and 2/3 (for $rest).
  shuffle($main_featured_visuals);
  $main_featured_visuals_above = array_splice($main_featured_visuals, 0, floor(count($main_featured_visuals) / 3));

  // Seed with created time of first node for consistent results that change only when result set changes.
  //srand(count($nodes)); mt_srand(count($nodes));

  // Split off newest few for chronological display on very top.
  $newest = array_splice($nodes, 0, 5);
  $newest_2 = array_splice($nodes, 0, 7);

  // Shuffle remaining
  shuffle($nodes);
  _exhibition_content_array_random_insert($nodes, $main_featured_visuals, 20);
  _exhibition_content_array_random_insert($nodes, $newest_2, 0, 14);
  $nodes= array_merge($newest, $nodes);
  _exhibition_content_array_random_insert($nodes, $main_featured_visuals_above, 6, 28);
  _exhibition_content_array_random_insert($nodes, exhibition_content_get_intro_content(), 8, 28);

  // Render nodes
  foreach ($nodes as $node) {
    $render = entity_view('node', array($node), 'teaser');
    $build[] = $render;
  }

  return $build;
}


/**
 * Randomly distributed one set of items into another set of items.
 *
 * @param $array_heap
 * @param $array_inserts
 * @param $min_pos
 * @param int $max_pos
 */
function _exhibition_content_array_random_insert(&$array_heap, $array_inserts, $min_pos, $max_pos = 0) {
  if (!$max_pos) { $max_pos = count($array_heap); }
  $stepwidth = max(1, floor(($max_pos-$min_pos) / count($array_inserts)));
  foreach(array_values($array_inserts) as $delta => $item) {
    $pos = rand($min_pos, max($min_pos, $min_pos+$stepwidth-1));
    array_splice($array_heap, $pos, 0, array($item));
    //  $min_pos = $pos+2;
    $min_pos += $stepwidth;
    $stepwidth += floor($delta / count($array_inserts));
  }
}


/**
 * Assembles the intro tile for the frontpage.
 */
function exhibition_content_get_intro_content() {
  $nodes = array();
  // @Todo add 3 (or the "promoted") text tiles (maybe with random color-/size-assignment?)
  foreach(array('intro_title', 'intro_info', 'intro_engage') as $title_id) {
    $intro_node = exhibition_base_get_entity('node', FALSE, array('type' => 'detail', 'title' => $title_id));
    if (is_object($intro_node)) {
      $intro_node->style_override = "intro-tile";
      $intro_node->style_additional = $title_id;
      $nodes[] = $intro_node;
    }
  }

  return $nodes;
}


/**
 * Get a field from a detail node.
 */
function exhibition_content_get_detail_content($title_id) {
  $node = exhibition_base_get_entity('node', FALSE, array('type' => 'detail', 'title' => $title_id));
  $lang = field_language('node', $node, 'field_text');
  if (is_object($node) && isset($node->field_text[$lang])) {
    return $node->field_text[$lang][0]['value'];
  }
  else {
    return '';
  }
}


/**
 * Get the overview page content
 *
 */
function exhibition_content_get_portrait_navigation() {
  $build = array();
  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', array('visual'))
    ->propertyCondition('status', NODE_PUBLISHED)
    //->propertyCondition('promote', NODE_PROMOTED)
    ->fieldCondition('field_visual_purpose', 'value', 'featured')
    ->propertyOrderBy('created', 'DESC')
    ->range(0, 200);

  $result = $query->execute();

  $current_node = (('node' == arg(0)) && (is_numeric(arg(1)))) ? arg(1) : -1;

  if (isset($result['node'])) {
    $nodes = entity_load('node', array_keys($result['node']));
    foreach($nodes as $node) {
      if ($parent_id = isset($node->field_parent_content[LANGUAGE_NONE][0]['target_id']) ? $node->field_parent_content[LANGUAGE_NONE][0]['target_id'] : 0) {
        $parent_node = node_load($parent_id);
        $parent_key = isset($parent_node->field_priority) ? $parent_node->field_priority[LANGUAGE_NONE][0]['value'] : 0;
        $parent_key = str_pad($parent_key, 10, '0', STR_PAD_LEFT) . '-' . str_pad($parent_node->nid, 10, '0', STR_PAD_LEFT);

      // Set this visual node as portrait navigation thumbnail for this parent, if
        // either no visual has been chosen yet for that portrait parent
        // or this visual is from the most current epoch.
        if (   (!isset($build[$parent_key]) && isset($node->field_image_file[LANGUAGE_NONE]))
               ||
               (isset($node->field_epoch[LANGUAGE_NONE]) && (EXHIBITION_BASE_ID_EPOCH_MOST_RECENT == $node->field_epoch[LANGUAGE_NONE][0]['tid']))
        ) {
          $file = $node->field_image_file[LANGUAGE_NONE][0]['uri'];
          $build[$parent_key] = array(
            'node' => $node,
            '#theme' => 'image_formatter',
            '#image_style' => 'teaser_square_tiny',
            '#item' => array(
              'uri' => $file,
            ),
            '#path' => array(
              'path' => 'node/' . $parent_id,
              'options' => array(
                'attributes' => array(
                  'class' => array(($parent_id == $current_node) ? 'active' : 'inactive'),
                  'title' => '',
                ),
              ),
            ),
          );

        }
      }
    }
  }
  ksort($build);
  return $build;
}


// END OF FILE marker.
