<div class="page-footer">
  <div class="extro blurb">
    <h2><?php print t('Our View - 12 women From Srebrenica'); ?></h2>
    <p>
    We are a group of 12 women from Srebrenica,
    using cell phone photography to talk about our personal life in Bosnia nowadays.
    We've been working together in the years 2000 and 2005.
    Outcome was an internationally respected exhibition and a book.
    This is the online exhibition with work of 2000 and 2005 and the very very new pictures from 2015, growing day by day by a selection of our Instagram feed.
    </p>
    <p><?php print t('Talk too, with us:'); ?></p>

    <div class="follow">
      <ul>
        <li><a class="instagram" href="https://instagram.com/everydaysrebrenica"><?php print t('See more #everydaySrebrenica on <b>Instagram</b>'); ?></a></li>
        <li><a class="facebook" href="http://www.facebook.com/everydaysrebrenica"><?php print t('Follow us on <b>Facebook</b>'); ?></a></li>
        <li><a class="amazon" href="http://www.amazon.de/gp/product/3937014322/ref=olp_product_details?ie=UTF8&me=http://www.amazon.de/gp/product/3937014322/ref=olp_product_details?ie=UTF8&me="><?php print t('Look up the <b>Book on Amazon</b>'); ?></a></li>
        <li><a class="email" href="mailto:srebrenica@barbara-hartmann.de"><?php print('Send an <b>E-Mail</b>'); ?></a></li>
      </ul>
    </div>
    <p>Use our hashtag #everydaysrebrenica for your Instagram-Photos, for <i>your</i> personal Srebrenica story.  ### We'd love to see your story, be about daily life in former Yugoslavia or from WW2 or greetings from Syria, Congo or any marginalized neighborhood...!
      Your Everyday Srebrenica. Hvala. Thank you. Your <a href="https://instagram.com/everydaysrebrenica"><?php print t('#EVERYDAYSREBRENICA'); ?></a>
    </p>

  </div>
</div>